### ISSUE TITLE
NextPercentBonus() ignores chanceOfOneMore

### ISSUE THREAD

**Issue by richard-sim** [BenMakesGames/RandomHelpers#1]
https://github.com/BenMakesGames/RandomHelpers/blob/beb1fb27db830d88ddf2eb91182faa720e9bbe72/BenMakesGames.RandomHelpers/RandomHelpers.cs#L154

It looks like returnedAmount should be incremented/decremented depending on chanceOfOneMore, not chanceOfOneMore itself.

**Comment by BenMakesGames** [comment]
! you're 100% correct! pushed the fix just now!
